apiVersion: apps/v1
kind: Deployment
metadata:
  name: generic-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: generic-app
  template:
    metadata:
      labels:
        app: generic-app
    spec:
      containers:
      - name: generic-container
        image: YOUR_DOCKER_IMAGE
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: generic-service
spec:
  selector:
    app: generic-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
